Repository AY2122S2-CS2103T-W09-4/tp, pull requests merged in 2022-03, with the labels that each got.

#44 Implement Archive command
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Story

#50 Edit add command example
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug

#47 Implement Find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/model/person/StudentIdContainsKeywordsPredicate.java
Labels: type.Story

#90 Update index.md to include TAPA's info
  README.md
  docs/AboutUs.md
  docs/index.md
Labels: severity.VeryLow

#97 Change the format in the GUI
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#101 Implement progress command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/ManualMessages.java
  src/main/java/seedu/address/logic/commands/ManualCommand.java
  src/main/java/seedu/address/logic/commands/ProgressCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ProgressCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/TaskList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/commons/core/ManualMessages.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.High

#116 Fix testcases
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.Low

#118 Add extra checks in TaskCommandParser
  src/main/java/seedu/address/logic/parser/TaskCommandParser.java
Labels: severity.Medium

#126 Implement multi delete by indices
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Story, priority.Medium

#124 Fix bug in add command
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram-1.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.Medium

#131 Fix minor bugs
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/ManualMessages.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/commons/core/ManualMessages.java
Labels: type.Bug, severity.VeryLow

#120 Implement History and Undo commands
  src/main/java/seedu/address/commons/core/ManualMessages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ConfirmClearCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ManualCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/AddressBookHistory.java
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/TelegramHandle.java
  src/test/java/seedu/address/commons/core/ManualMessages.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High
